### PR TITLE
Modularized menus and menu components

### PR DESCRIPTION
**Pull request by MartinMuzatko**
- Level (map as HTML5 name for element is already taken by W3C)
- Player - Menu consisting of latest maps played, some statistics - basically a hub to get to your most used resources

### CODE REVIEW

**Comment by Croydon** [comment]
What is the point of PRs if you don't wait for feedback? :)

**Comment by MartinMuzatko** [comment]
Because I work from my fork and the repo is for the demo/prototype anyway :)
But if you suggest another workflow, please let me know @Croydon

**Comment by Croydon** [comment]
@MartinMuzatko What about creating a branch directly in this repo and then merge it without a PR?

**Comment by MartinMuzatko** [comment]
Works for me, I will do that in the future :) @Croydon

**Pull request merged**
